[{"lineNumber": 4, "col_offset": 16, "nodeName": "Exception", "type": "Type[Exception]"}, {"lineNumber": 8, "col_offset": 23, "nodeName": "ValueError", "type": "Type[ValueError]"}, {"lineNumber": 15, "col_offset": 25, "nodeName": "RuntimeWarning", "type": "Type[RuntimeWarning]"}, {"lineNumber": 19, "col_offset": 25, "nodeName": "RuntimeWarning", "type": "Type[RuntimeWarning]"}, {"lineNumber": 23, "col_offset": 27, "nodeName": "RuntimeWarning", "type": "Type[RuntimeWarning]"}, {"lineNumber": 12, "col_offset": 8, "nodeName": "original_exception", "type": "Any"}, {"lineNumber": 12, "col_offset": 34, "nodeName": "original_exception", "type": "Any"}, {"lineNumber": 11, "col_offset": 8, "nodeName": "__init__", "type": "Callable[..., None]"}, {"lineNumber": 12, "col_offset": 8, "nodeName": "self", "type": "ConvergenceError"}, {"lineNumber": 11, "col_offset": 47, "nodeName": "msg", "type": "Any"}, {"lineNumber": 11, "col_offset": 8, "nodeName": "super", "type": "Type[super]"}, {"lineNumber": 11, "col_offset": 14, "nodeName": "ConvergenceError", "type": "Type[ConvergenceError]"}, {"lineNumber": 11, "col_offset": 32, "nodeName": "self", "type": "ConvergenceError"}, {"lineNumber": 11, "col_offset": 60, "nodeName": "original_exception", "type": "Any"}]