[{"lineNumber": 1, "col_offset": 29, "nodeName": "Exception", "type": "Type[Exception]"}, {"lineNumber": 7, "col_offset": 25, "nodeName": "ContainerExecException", "type": "Type[ContainerExecException]"}, {"lineNumber": 13, "col_offset": 17, "nodeName": "ContainerExecException", "type": "Type[ContainerExecException]"}, {"lineNumber": 3, "col_offset": 8, "nodeName": "message", "type": "Any"}, {"lineNumber": 3, "col_offset": 23, "nodeName": "message", "type": "Any"}, {"lineNumber": 3, "col_offset": 8, "nodeName": "self", "type": "ContainerExecException"}, {"lineNumber": 4, "col_offset": 8, "nodeName": "__init__", "type": "Callable[..., None]"}, {"lineNumber": 4, "col_offset": 8, "nodeName": "super", "type": "Type[super]"}, {"lineNumber": 4, "col_offset": 14, "nodeName": "ContainerExecException", "type": "Type[ContainerExecException]"}, {"lineNumber": 4, "col_offset": 38, "nodeName": "self", "type": "ContainerExecException"}]